### PR TITLE
Remove python2 support.

### PR DESCRIPTION
**Pull request by wxsBSD**
Python2 is a dead language, we should no longer be supporting it. To that end,
this commit removes python2 support by doing the following:

If you run setup.py with a python2 interpreter, it will error out.

The pip runtime is now enforcing a required python version of 3 or higher.

Remove all preprocessor macros for supporting both python2 and python3. They are
all now python3 only.

I also removed the PYTHON_API_VERSION check since that is very old (as far as I
can tell that API version was first set in 1997).

### CODE REVIEW

**Comment by wxsBSD** [comment]
I know we've talked about this eventually happening but I thought I would get a jump start on it for when you are ready to finally remove python2 support. I'm happy to leave this PR open and keep it updated until such time. I don't think it belongs in the 4.0 release since we haven't given any heads up that this is coming, but maybe in a future 4.x release we can merge this.

This has only been lightly tested manually by me, and I also made sure all tests pass.

**Comment by plusvic** [comment]
That's the idea. Python 2.x won't be supported starting with YARA v 4.0, but only in the sense that no effort will be made to make it work. For example,  Windows installers for Python 2.x are not generated anymore because that requires using Visual C++ 9.0 which doesn't support C99. But for the time being I don't want to prevent people from using it with Python 2.x if it works without doing anything.

**Comment by plusvic** [comment]
For the time being we are not actively removing support for Python 2.x.

**Comment by wxsBSD** [comment]
I had mostly forgot about this PR. When you're ready to remove it I'll do the work!

**Pull request closed without merging**
